using System;
using Sixty502DotNet;

class Program
{
    static void Main(string[] args)
    {
        var assembler = new Z80Assembler();
        
        // Test LD HL, 3 instruction
        string testCode = "LD HL, 3";
        
        Console.WriteLine($"Testing: {testCode}");
        var result = assembler.Assemble(testCode);
        
        if (result.IsSuccess)
        {
            var bytes = result.Value.Binary;
            Console.WriteLine($"Generated bytes ({bytes.Length}): {string.Join(" ", bytes.Select(b => $"0x{b:X2}"))}");
            
            // Expected: 0x21 0x03 0x00 (opcode, low byte, high byte)
            if (bytes.Length >= 3)
            {
                Console.WriteLine($"Opcode: 0x{bytes[0]:X2} (expected: 0x21)");
                Console.WriteLine($"Low byte: 0x{bytes[1]:X2} (expected: 0x03)");  
                Console.WriteLine($"High byte: 0x{bytes[2]:X2} (expected: 0x00)");
                
                if (bytes[0] == 0x21 && bytes[1] == 0x03 && bytes[2] == 0x00)
                {
                    Console.WriteLine("✓ Assembly correct!");
                }
                else
                {
                    Console.WriteLine("✗ Assembly incorrect!");
                }
            }
        }
        else
        {
            Console.WriteLine($"Assembly failed: {result.Error}");
        }
    }
}
